version: '3.3'
services:
  deploy:
    build: .
    ports:
     - 9005:9005
     - 5000:5000
    volumes:
     - .:/usr/src/app
     - /usr/src/app/firebase/functions/node_modules
  test:
    build: .
    working_dir: /usr/src/app/firebase/functions
    command: npm test -- --watch
    volumes:
     - .:/usr/src/app
     - /usr/src/app/firebase/functions/node_modules
  token:
    build: .
    command: firebase login:ci
    volumes:
     - .:/usr/src/app
     - /usr/src/app/firebase/functions/node_modules
